apiVersion: v1
kind: Service
metadata:
  name: oracle-host-app-service
  labels:
    app: oracle-host-app
spec:
  type: LoadBalancer
  selector:
    app: oracle-host-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080