apiVersion: v1
entries:
  Chart-Oracle-Host-App:
  - apiVersion: v1
    appVersion: 1.2.3
    created: "2021-11-14T22:11:52.356559+02:00"
    description: Helm chart for Kubernetes
    digest: 6c35684efff2c7c20cab4bd037f618144a9bd89db0c19c906bab564cc3644397
    keywords:
    - java
    - http
    - spring
    name: Chart-Oracle-Host-App
    type: application
    urls:
    - Chart-Oracle-Host-App-0.1.2.tgz
    version: 0.1.2
generated: "2021-11-14T22:11:52.355909+02:00"
